### ISSUE TITLE
Remove Lite from the name

### ISSUE THREAD

**Issue by monkeymademe** [monkeymademe/picamera2-WebUI#38]
this thing is turning into a monster.... maybe just forget the idea of lite and just have one project

**Comment by geerlingguy** [comment]
Heh for sure. I wasn't expecting much at all based on the name.

Then I downloaded it, ran it... and realized this is the nicest web camera GUI I've ever used on a Pi! Setup was a breeze too (even though I was on Lite Pi OS).

**Comment by geerlingguy** [comment]
@monkeymademe - FYI, I hope to use this project in a video I'm working on next week — if you change the name of the project by Monday that'd be great in terms of me mentioning it as just "picamera2-WebUI" :)

**Comment by monkeymademe** [comment]
Aw man thats awesome! Actually I am working on the next version right now which will be a huge change in how the UI will work... I will get my skates on to get it up... In terms of the name I am dropping the lite for sure...

**Comment by monkeymademe** [comment]
@geerlingguy - Aw man thats awesome! Actually I am working on the next version right now which will be a huge change in how the UI will work... I will get my skates on to get it up... In terms of the name I am dropping the lite for sure...

**Comment by geerlingguy** [comment]
That's awesome! And I can't remember if it was @Tschucker or maybe the booth next to his running an 8mm film scanner—one of them was using this same utility for a web UI for the camera in one demo at Open Sauce!

**Comment by monkeymademe** [comment]
'Lite' has been removed
