### ISSUE TITLE
Add `static/*` to .gitignore

### ISSUE THREAD

**Issue by geerlingguy** [monkeymademe/picamera2-WebUI#45]
**Is your feature request related to a problem? Please describe.**

I noticed after taking a Timelapse within the project folder, my git checkout had a bunch of untracked files inside `static/gallery/*`

```
pi@pistream:~/picamera2-WebUI-Lite $ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   camera-config.json
	deleted:    static/gallery/pimage_1709139459.jpg

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.venv/
	static/gallery/pimage_1717817415.jpg
	static/gallery/pimage_1717954818.jpg
	static/gallery/pimage_1717954820.jpg
	static/gallery/pimage_1717954822.jpg
	static/gallery/pimage_1717954824.jpg
	static/gallery/pimage_1717954826.jpg
	static/gallery/pimage_1717954828.jpg
	static/gallery/pimage_1717954830.jpg
	static/gallery/pimage_1717954832.jpg
	static/gallery/pimage_1717954834.jpg
```

**Describe the solution you'd like**

It may be good to have a `.gitignore` with:

```
static/*
```

That would allow me to store the static images in the project folder without having a bunch of untracked files show up.

It may also be good to add:

```
.venv/*
```

**Describe alternatives you've considered**

I could clone the repo and maintain a fork with the changes, or just ignore git history entirely (though that can be a little annoying).

**Additional context**

N/A

**Comment by monkeymademe** [comment]
Oh this was added since v1.0.1

**Comment by geerlingguy** [comment]
Thanks!
