### ISSUE TITLE
Web Server Port Number

### ISSUE THREAD

**Issue by dalogue1** [monkeymademe/picamera2-WebUI#59]
I am running the picamera2-WebUI on the same machine as another application with a Web Server.
 (i.e.    BirdNET-Pi.      https://github.com/Nachtzuster/BirdNET-Pi ) and it already is using port 8080.  

It would be nice to pass the port number into the app.py as an argument and to default to 8080 if the argument was not provided. 

Not a big deal because it is literally the final line of the script and is easy to change.

**Comment by monkeymademe** [comment]
This is an easy fix I will look at it on the next release (very soon)

**Comment by monkeymademe** [comment]
Give this ago - if ok then I will close this ticket

https://github.com/monkeymademe/picamera2-WebUI/commit/507a0e5ff80fa1433760e4ec8556491f40fa967b

**Comment by monkeymademe** [comment]
Released to https://github.com/monkeymademe/picamera2-WebUI/releases/tag/v1.0.1

**Comment by dalogue1** [comment]
It works great!
