### ISSUE TITLE
Version 1.0.0 Testing

### ISSUE THREAD

**Issue by dalogue1** [monkeymademe/picamera2-WebUI#63]
I tested the new version 1.0.0 of the application and the controls do not appear to work except for Orientation. Is there a button I need to press to have the changes take effect immediately? Also, the load and save settings does not appear to work. I have to stop/and start the service to have changes take affect.

**Comment by monkeymademe** [comment]
Fixed with this merge - https://github.com/monkeymademe/picamera2-WebUI/pull/64/commits 

sorry about that bad merging before

New version https://github.com/monkeymademe/picamera2-WebUI/releases/tag/v1.0.1 is out
