### ISSUE TITLE
Error on Load/Save Camera Settings dialog

### ISSUE THREAD

**Issue by dalogue1** [monkeymademe/picamera2-WebUI#69]
There is a problem wit the text box width on the Load/Save Camera Settings dialog. See image:

![image](https://github.com/user-attachments/assets/b67ea82e-04ff-4a7e-af0f-5596bd6112d0)

I verified that the save and load config works.  The text field only displays one character wide though.

**Comment by monkeymademe** [comment]
Fixed https://github.com/monkeymademe/picamera2-WebUI/commit/e38af6f719e3c996f01b168bb9276579757476f0
