### ISSUE TITLE
Button Update preview doesn't refresh the image on the Home page

### ISSUE THREAD

**Issue by AleksanderKruecken** [monkeymademe/picamera2-WebUI#75]
**Describe the bug**
If I press the button 'Update preview' the picture in the Home tab doesn't change. I have to refresh the page (F5) so that the new image appers.

I would expect that after pressing the 'Update preview' the picture in the Home tab would automaticaly refresh 
I have Rasberry pi bookworm running on RPI Zero 2W, Chrome browser, app version 1.0.2-2-g34fc6be

**Comment by monkeymademe** [comment]
Yeah sorry it was a planned feature but slipped from being polished. Its in now https://github.com/monkeymademe/picamera2-WebUI/commit/59ea9b72fee243f74909d39178378349a83eaa07
